### ISSUE TITLE
Rename the plugin?

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-KeyLogger#1]
The name `KeyLogger` is [not corporate friendly](https://github.com/keyboardio/Arduino-Boards/commit/3833069604f337f43fc98609eccf065b3e19a1ae), which is why this plugin has been removed from `Arduino-Boards`. While I would not want to put it back under a different name (as we should not have a keylogger in the set of common modules, too dangerous), for those who do want this feature, a better name would perhaps make it less scary.

I was thinking `Kaleidoscope-Lumberjack`, because of logs.

(/cc @obra)

**Comment by obra** [comment]
Part of the reason i sort of want to keep the current name is that it means -nobody- can misunderstand what it does. In this case, that’s extra important.

**Comment by algernon** [comment]
That makes sense, and I got similar feedback from others too. Convinced!

Thanks!
