### ISSUE TITLE
Measuring keypress duration

### ISSUE THREAD

**Issue by To1ne** [keyboardio/Kaleidoscope-KeyLogger#2]
Would it be possible to log the duration of the keypress, instead of the down and up events separately?

So instead of:

```
KL: row=1, col=2, pressed=1, defaultLayer=0, layerState=1, mappedKey.flags=0, mappedKey.keyCode=ff
KL: row=1, col=2, pressed=0, defaultLayer=0, layerState=1, mappedKey.flags=0, mappedKey.keyCode=ff
```

This:

```
KL: row=1, col=2, duration=123, defaultLayer=0, layerState=1, mappedKey.flags=0, mappedKey.keyCode=ff
```

With `duration` being the duration in milliseconds?

Or would it be better to measure timing on the host? I'm not sure if the latency due to the serial protocol would have influence on that?

**Comment by algernon** [comment]
It would be very costy to measure duration key by key. At best, I can add a timestamp, and you can compute the duration on the host.

**Comment by To1ne** [comment]
Cool! Thanks!!!

**Comment by obra** [comment]
Toon, What’s your use case here?

One thing we could do with a different technique is to log any report from the key scanner that shows a change, along with a time stamp. it won’t tell you which logical key pressed  but might still be useful

**Comment by To1ne** [comment]
I'm not sure what you describe would be useful.

But I'm not sure yet. I want to log metrics over a long period of time, so having the press duration might be useful to see progress over time.

**Comment by obra** [comment]
For long-term metrics, I do wonder if host-side keylogging will be easier
and more reliable.

**Comment by To1ne** [comment]
Yeah sure, I need to do something host-side anyway. I was just wondering if I could rely on the timing of the messages sent by the M01?

**Comment by obra** [comment]
There will be jitter and latency. How exact do you want it?

**Comment by To1ne** [comment]
I don't know, what is feasible? Maybe 250ms resolution is enough, since I'm using the SpaceCadet plugin with 250ms timeout.
